# Generated by Django 5.2.6 on 2025-10-03 03:25

import catalog.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='Unidade')),
                ('ncm', models.CharField(blank=True, max_length=8, validators=[catalog.validators.validate_ncm], verbose_name='NCM')),
                ('origin', models.CharField(blank=True, max_length=50, verbose_name='Origem')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Preço')),
                ('ipi_fixed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Valor IPI fixo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(blank=True, max_length=30, verbose_name='Situação')),
                ('stock_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Estoque')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Preço de custo')),
                ('supplier_code', models.CharField(blank=True, max_length=100, verbose_name='Cód no fornecedor')),
                ('supplier_name', models.CharField(blank=True, max_length=150, verbose_name='Fornecedor')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Localização')),
                ('bling_extra', models.JSONField(blank=True, default=dict, verbose_name='Extras Bling (colunas 16–45)')),
                ('external_link', models.URLField(blank=True, max_length=500, verbose_name='Link Externo')),
                ('warranty_months_supplier', models.IntegerField(default=0, verbose_name='Meses Garantia no Fornecedor')),
                ('clone_from_parent', models.BooleanField(default=False, verbose_name='Clonar dados do pai')),
                ('product_condition', models.CharField(blank=True, max_length=30, verbose_name='Condição do produto')),
                ('free_shipping', models.BooleanField(default=False, verbose_name='Frete Grátis')),
                ('fci_number', models.CharField(blank=True, max_length=36, verbose_name='Número FCI')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='Vídeo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('unit_of_measure', models.CharField(blank=True, max_length=20, verbose_name='Unidade de medida')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Preço de compra')),
                ('icms_st_base_retencao', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[catalog.validators.validate_nonnegative], verbose_name='Valor base ICMS ST p/ retenção')),
                ('icms_st_valor_retencao', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[catalog.validators.validate_nonnegative], verbose_name='Valor ICMS ST p/ retenção')),
                ('icms_proprio_substituto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[catalog.validators.validate_nonnegative], verbose_name='Valor ICMS próprio do substituto')),
                ('product_category', models.CharField(blank=True, max_length=150, verbose_name='Categoria do produto')),
                ('extra_info', models.TextField(blank=True, verbose_name='Informações Adicionais')),
                ('cest', models.CharField(blank=True, max_length=7, verbose_name='CEST')),
                ('gtin', models.CharField(blank=True, max_length=14, validators=[catalog.validators.validate_gtin], verbose_name='GTIN/EAN')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('width_cm', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Largura (cm)')),
                ('height_cm', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Altura (cm)')),
                ('length_cm', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Profundidade (cm)')),
                ('weight_net', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Peso líquido (kg)')),
                ('weight_gross', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Peso bruto (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['sku'],
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ncm'], name='catalog_pro_ncm_d4331f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['gtin'], name='catalog_pro_gtin_10f25d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_category'], name='catalog_pro_product_2cde52_idx'),
        ),
    ]
