# Generated by Django 5.2.6 on 2025-10-03 03:48

import catalog.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_delete_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Preço de custo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icms_proprio_substituto',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, validators=[catalog.validators.validate_nonnegative], verbose_name='Valor ICMS próprio do substituto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icms_st_base_retencao',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, validators=[catalog.validators.validate_nonnegative], verbose_name='Valor base ICMS ST p/ retenção'),
        ),
        migrations.AlterField(
            model_name='product',
            name='icms_st_valor_retencao',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, validators=[catalog.validators.validate_nonnegative], verbose_name='Valor ICMS ST p/ retenção'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ipi_fixed',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Valor IPI fixo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Profundidade (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Preço de compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_months_supplier',
            field=models.IntegerField(blank=True, default=0, verbose_name='Meses Garantia no Fornecedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_gross',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Peso bruto (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_net',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Peso líquido (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, validators=[catalog.validators.validate_nonnegative], verbose_name='Largura (cm)'),
        ),
    ]
