# Generated by Django 5.2.6 on 2025-10-08 02:47

import catalog.validators
import catalog.validators.ean
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_cost_price_alter_product_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variations_grid',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(blank=True, max_length=50, verbose_name='Tamanho (nome)')),
                ('color_name', models.CharField(blank=True, max_length=50, verbose_name='Cor (nome)')),
                ('size_code', models.CharField(blank=True, max_length=2, verbose_name='Tamanho (código 2d)')),
                ('color_code', models.CharField(blank=True, max_length=2, verbose_name='Cor (código 2d)')),
                ('sku', models.CharField(blank=True, max_length=80, unique=True, verbose_name='SKU variante')),
                ('ean13', models.CharField(blank=True, max_length=13, unique=True, validators=[catalog.validators.ean.validate_ean13], verbose_name='EAN-13')),
                ('stock_qty', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Estoque')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, validators=[catalog.validators.validate_nonnegative], verbose_name='Preço override')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Variante de produto',
                'verbose_name_plural': 'Variantes de produto',
                'indexes': [models.Index(fields=['product'], name='catalog_pro_product_460665_idx'), models.Index(fields=['sku'], name='catalog_pro_sku_187601_idx'), models.Index(fields=['ean13'], name='catalog_pro_ean13_20a282_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'size_name', 'color_name'), name='uniq_variant_by_names_per_product')],
            },
        ),
    ]
