# Generated by Django 5.2.6 on 2025-11-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_variations_grid_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='desc_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='desc_short',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_real_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
