# Generated by Django 5.2.6 on 2025-10-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True, verbose_name='Chave do papel')),
                ('label', models.CharField(max_length=80, verbose_name='Nome do papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Papel de colaborador',
                'verbose_name_plural': 'Papéis de colaborador',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collaborators', to='people.collaboratorrole', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='people_coll_is_acti_baef54_idx')],
            },
        ),
    ]
